export default {
  // Objects
  obj: [
    { word: 'bed', emoji: '🛏', translation: 'łóżko' },
    { word: 'chair', emoji: '🪑', translation: 'krzesło' },
    { word: 'pillow', emoji: '🛌', translation: 'poduszka' },
    { word: 'toilet', emoji: '🚽', translation: 'toaleta' },
    { word: 'blanket', emoji: '🛌', translation: 'koc' },
    { word: 'window', emoji: '🪟', translation: 'okno' },
    { word: 'key', emoji: '🔑', translation: 'klucz' },
    { word: 'door', emoji: '🚪', translation: 'drwzi' },
    { word: 'bottle', emoji: '🍼', translation: 'butelka' },
    { word: 'phone', emoji: '📞', translation: 'telefon' },
    { word: 'computer', emoji: '🖥', translation: 'komputer' },
    { word: 'apple', emoji: '🍏', translation: 'jabłko' },
    { word: 'bag', emoji: '👜', translation: 'torba' },
    { word: 'book', emoji: '📔', translation: 'książka' },
    { word: 'glasses', emoji: '👓', translation: 'okulary' },
    { word: 'money', emoji: '💵', translation: 'pieniądze' },
    { word: 'clothes', emoji: '👚', translation: 'odzież' },
    { word: 'car', emoji: '🚗', translation: 'samochód' },
    { word: 'train', emoji: '🚄', translation: 'pociąg' },
    { word: 'bus', emoji: '🚌', translation: 'autobus' },
    { word: 'shoes', emoji: '👞', translation: 'buty' },
    { word: 'tree', emoji: '🌳', translation: 'drzewo' },
    { word: 'road', emoji: '🛣', translation: 'droga' },
    { word: 'street', emoji: '🛣', translation: 'ulica' },
    { word: 'clock', emoji: '🕰', translation: 'zegar' },
    { word: 'watch', emoji: '⌚️', translation: 'zegarek' },
    { word: 'hair', emoji: '💇‍♀️', translation: 'włosy' },
    { word: 'eyes', emoji: '👀', translation: 'oczy' },
    { word: 'mouth', emoji: '👄', translation: 'usta' },
    { word: 'nose', emoji: '👃', translation: 'nos' },
    { word: 'ears', emoji: '👂', translation: 'uszy' },
    { word: 'vegetables', emoji: '🥦', translation: 'warzywa' },
    { word: 'groceries', emoji: '🥖', translation: 'produkty spożywcze' },
    { word: 'shops', emoji: '🛍', translation: 'sklepy' },
    { word: 'church', emoji: '⛪️', translation: 'kościół' },
    { word: 'pen', emoji: '🖊', translation: 'długopis' },
    { word: 'pencil', emoji: '✏️', translation: 'ołówek' },
    { word: 'building', emoji: '🏢', translation: 'budynek' },
    { word: 'ticket', emoji: '🏷', translation: 'bilet' },
    { word: 'elevator', emoji: '🛗', translation: 'winda' },
    { word: 'stairs', emoji: '𓊍', translation: 'schody' },
    { word: 'scissors', emoji: '✂️', translation: 'nożyce' },
    { word: 'ice cream', emoji: '🍦', translation: 'lody' },
    { word: 'food', emoji: '🍱', translation: 'jedzenie' },
    { word: 'couch', emoji: '🛋', translation: 'kanapa' },
    { word: 'painting', emoji: '🖼', translation: 'obraz' },
    { word: 'gift', emoji: '🎁', translation: 'prezent' },
    { word: 'television', emoji: '📺', translation: 'telewizja' },
    { word: 'lamp', emoji: '💡', translation: 'lampa' },
    { word: 'seat', emoji: '💺', translation: 'siedzenie' },
    { word: 'board', emoji: '👩‍🏫', translation: 'tablica' }
  ],
  // Locations
  loc: [
    { word: 'somewhere', emoji: '🕒', translation: 'gdzieś' },
    { word: 'anywhere', emoji: '🕒', translation: 'gdziekolwiek' },
    { word: 'nowhere', emoji: '🕒', translation: 'nigdzie' },
    { word: 'elsewhere', emoji: '🕒', translation: 'gdzie indziej' },
    { word: 'down', emoji: '⬇️', translation: 'na dół' },
    { word: 'up', emoji: '⬆️', translation: 'w górę' },
    { word: 'in', emoji: '🕒', translation: 'w' },
    { word: 'out', emoji: '🕒', translation: 'na zewnątrz' },
    { word: 'near', emoji: '🕒', translation: 'blisko' },
    { word: 'far', emoji: '🕒', translation: 'daleko' },
    { word: 'on', emoji: '🕒', translation: 'na' },
    { word: 'over', emoji: '🕒', translation: 'przez' },
    { word: 'towards', emoji: '🕒', translation: 'w stronę' },
    { word: 'under', emoji: '🕒', translation: 'pod' },
    { word: 'above', emoji: '🕒', translation: 'nad' },
    { word: 'behind', emoji: '🕒', translation: 'za' },
    { word: 'in front of', emoji: '🕒', translation: 'z przodu' },
    { word: 'next to', emoji: '🕒', translation: 'obok' },
    { word: 'indoors', emoji: '🕒', translation: 'wewnątrz' },
    { word: 'outdoors', emoji: '🕒', translation: 'na dworze' },
    { word: 'nearby', emoji: '🕒', translation: 'w pobliżu' },
    { word: 'here', emoji: '🕒', translation: 'tutaj' },
    { word: 'there', emoji: '🕒', translation: 'tam' },
    { word: 'back', emoji: '🕒', translation: 'z powrotem' },
    { word: 'inside', emoji: '🕒', translation: 'w środku' },
    { word: 'outside', emoji: '🕒', translation: 'poza' },
    { word: 'below', emoji: '🕒', translation: 'poniżej' },
    { word: 'next door', emoji: '🕒', translation: 'następne drzwi' },
    { word: 'east', emoji: '🕒', translation: 'wschód' },
    { word: 'west', emoji: '🕒', translation: 'zachód' },
    { word: 'north', emoji: '🕒', translation: 'północ' },
    { word: 'south', emoji: '🕒', translation: 'południe' },
    { word: 'at home', emoji: '🕒', translation: 'w domu' },
    { word: 'at work', emoji: '🕒', translation: 'w pracy' },
    { word: 'in the neighborhood', emoji: '🕒', translation: 'w sąsiedztwie' },
  ],
  // Time words
  time: [
    { word: 'yesterday', emoji: '🕒', translation: 'wczoraj' },
    { word: 'today', emoji: '🕒', translation: 'dziś' },
    { word: 'tomorrow', emoji: '🕒', translation: 'jutro' },
    { word: 'tonight', emoji: '🕒', translation: 'dziś wieczorem' },
    { word: 'in the morning', emoji: '🕒', translation: 'rankiem' },
    { word: 'in the evening', emoji: '🕒', translation: 'wieczorem' },
    { word: 'at noon', emoji: '🕒', translation: 'w południe' },
    { word: 'next week', emoji: '🕒', translation: 'w następnym tygodniu' },
    { word: 'next month', emoji: '🕒', translation: 'w następnym miesiącu' },
    { word: 'last week', emoji: '🕒', translation: 'zeszły tydzień' },
    { word: 'last month', emoji: '🕒', translation: 'w zeszłym miesiącu' },
    { word: 'last night', emoji: '🕒', translation: 'ostatnia noc' },
    { word: 'then', emoji: '🕒', translation: 'następnie' },
    { word: 'another time', emoji: '🕒', translation: 'innym razem' },
    { word: 'earlier', emoji: '🕒', translation: 'wcześniej' },
    { word: 'later', emoji: '🕒', translation: 'później' },
    { word: 'previously', emoji: '🕒', translation: 'poprzednio' },
    { word: 'back then', emoji: '🕒', translation: 'wtedy' },
    { word: 'always', emoji: '🕒', translation: 'zawsze' },
    { word: 'never', emoji: '🕒', translation: 'nigdy' },
    { word: 'often', emoji: '🕒', translation: 'często' },
    { word: 'already', emoji: '🕒', translation: 'już' },
    { word: 'daily', emoji: '🕒', translation: 'codzienny' },
    { word: 'before', emoji: '🕒', translation: 'zanim' },
    { word: 'after', emoji: '🕒', translation: 'po' },
    { word: 'constantly', emoji: '🕒', translation: 'stale' },
    { word: 'in general', emoji: '🕒', translation: 'ogólnie' },
    { word: 'now', emoji: '🕒', translation: 'teraz' },
    { word: 'finally', emoji: '🕒', translation: 'wreszcie' },
    { word: 'rarely', emoji: '🕒', translation: 'rzadko' }
  ],
  // Normal verbs
  verb: [
    { word: 'eat', emoji: '🕒', translation: 'drwzi' },
    { word: 'drink', emoji: '🕒', translation: 'drwzi' },
    { word: 'clean', emoji: '🕒', translation: 'drwzi' },
    { word: 'sleep', emoji: '🕒', translation: 'drwzi' },
    { word: 'read', emoji: '🕒', translation: 'drwzi' },
    { word: 'dance', emoji: '🕒', translation: 'drwzi' },
    { word: 'drive', emoji: '🕒', translation: 'drwzi' },
    { word: 'listen', emoji: '🕒', translation: 'drwzi' },
    { word: 'hear', emoji: '🕒', translation: 'drwzi' },
    { word: 'smell', emoji: '🕒', translation: 'drwzi' },
    { word: 'taste', emoji: '🕒', translation: 'drwzi' },
    { word: 'feel', emoji: '🕒', translation: 'drwzi' },
    { word: 'see', emoji: '🕒', translation: 'drwzi' },
    { word: 'understand', emoji: '🕒', translation: 'drwzi' },
    { word: 'hope', emoji: '🕒', translation: 'drwzi' },
    { word: 'disagree', emoji: '🕒', translation: 'drwzi' },
    { word: 'agree', emoji: '🕒', translation: 'drwzi' },
    { word: 'value', emoji: '🕒', translation: 'drwzi' },
    { word: 'like', emoji: '🕒', translation: 'drwzi' },
    { word: 'love', emoji: '🕒', translation: 'drwzi' },
    { word: 'hate', emoji: '🕒', translation: 'drwzi' },
    { word: 'hire', emoji: '🕒', translation: 'drwzi' },
    { word: 'fire', emoji: '🕒', translation: 'drwzi' },
    { word: 'fight', emoji: '🕒', translation: 'drwzi' },
    { word: 'forgive', emoji: '🕒', translation: 'drwzi' },
    { word: 'forget', emoji: '🕒', translation: 'drwzi' },
    { word: 'save', emoji: '🕒', translation: 'drwzi' },
    { word: 'lose', emoji: '🕒', translation: 'drwzi' },
    { word: 'say', emoji: '🕒', translation: 'drwzi' },
  ],
  // Past verbs (I form)
  verp: [

  ],
  // Commands (imperative, you form)
  verc: [

  ],
  // Asks (you form)
  vera: [

  ],
  // Adjectives
  adj: [
    { word: 'kind', emoji: '😊', translation: 'uprzejmy' },
    { word: 'calm', emoji: '😌', translation: 'spokojna' },
    { word: 'stressed', emoji: '😣', translation: 'akcentowany' },
    { word: 'happy', emoji: '😀', translation: 'szczęśliwy' },
    { word: 'sad', emoji: '😔', translation: 'smutny' },
    { word: 'angry', emoji: '😡', translation: 'zły' },
    { word: 'scared', emoji: '😨', translation: 'przestraszony' },
    { word: 'surprised', emoji: '😱', translation: 'zaskoczony' },
    { word: 'generous', emoji: '🤗', translation: 'hojny' },
    { word: 'greedy', emoji: '😒', translation: 'chciwy' },
    { word: 'annoyed', emoji: '🙄', translation: 'zirytowany' },
    { word: 'smart', emoji: '🤓', translation: 'mądry' },
    { word: 'crazy', emoji: '🤪', translation: 'zwariowany' },
    { word: 'blonde', emoji: '👩', translation: 'blond' },
    { word: 'tall', emoji: '📏', translation: 'wysoki' },
    { word: 'short', emoji: '📏', translation: 'niski' },
    { word: 'sick', emoji: '🤒', translation: 'chory' },
    { word: 'injured', emoji: '🤕', translation: 'ranny' },
    { word: 'healthy', emoji: '', translation: 'zdrowy' },
    { word: 'rich', emoji: '💰', translation: 'bogaty' },
    { word: 'poor', emoji: '🏚', translation: 'słaby' },
    { word: 'old', emoji: '👵🏻', translation: 'stary' },
    { word: 'young', emoji: '👶', translation: 'młody' },
    { word: 'tired', emoji: '😪', translation: 'zmęczony' },
    { word: 'sleepy', emoji: '🥱', translation: 'młody' },
    { word: 'beautiful', emoji: '✨', translation: 'piękny' },
    { word: 'sweet', emoji: '🍬', translation: 'słodkie' },
    { word: 'lovely', emoji: '💕', translation: 'śliczny' },
    { word: 'sour', emoji: '😖', translation: 'kwaśny' },
    { word: 'bitter', emoji: '😖', translation: 'gorzki' },
    { word: 'mature', emoji: '💁‍♀️', translation: 'dojrzały' },
    { word: 'childish', emoji: '😜', translation: 'dziecinny' },
    { word: 'fast', emoji: '🐎', translation: 'szybki' },
    { word: 'slow', emoji: '🐌', translation: 'wolny' },
    { word: 'wide', emoji: '📏', translation: 'szeroki' },
    { word: 'narrow', emoji: '📏', translation: 'wąska' },
    { word: 'dizzy', emoji: '🥴', translation: 'oszołomiony' },
    { word: 'bright', emoji: '🌟', translation: 'jasny' },
    { word: 'dark', emoji: '🌑', translation: 'ciemny' },
    { word: 'safe', emoji: '🔒', translation: 'bezpieczny' },
    { word: 'dangerous', emoji: '💥', translation: 'niebezpieczny' },
    { word: 'boring', emoji: '😑', translation: 'nudy' },
    { word: 'exciting', emoji: '🤩', translation: 'ekscytujący' },
    { word: 'interesting', emoji: '🤔', translation: 'ciekawe' },
    { word: 'difficult', emoji: '😵', translation: 'trudny' },
    { word: 'easy', emoji: '😄', translation: 'łatwo' },
    { word: 'late', emoji: '🕒', translation: 'późno' },
    { word: 'early', emoji: '🕒', translation: 'wczesny' },
    { word: 'cold', emoji: '🥶', translation: 'przeziębienie' },
    { word: 'warm', emoji: '🍲', translation: 'ciepły' },
    { word: 'hot', emoji: '🥵', translation: 'gorący' },
    { word: 'tasty', emoji: '😋', translation: 'smaczny' },
    { word: 'disgusting', emoji: '🤢', translation: 'obrzydliwy' },
    { word: 'salty', emoji: '🧂', translation: 'słony' },
    { word: 'fine', emoji: '👌', translation: 'cienki' },
    { word: 'right', emoji: '👍', translation: 'prawo' },
    { word: 'wrong', emoji: '👎', translation: 'zło' },
    { word: 'talented', emoji: '⭐️', translation: 'utalentowany' },
    { word: 'professional', emoji: '👩‍🔬', translation: 'profesjonalny' },
    { word: 'casual', emoji: '💁‍♀️', translation: 'zwykły' },
    { word: 'elegant', emoji: '👔', translation: 'elegancki' }
  ],
  // Phrases
  phr: [
    'Please',
    'Good morning',
  ]
}
